name: Construire et Déployer l'API de prédiction des tags

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  construire-et-tester:
    runs-on: ubuntu-latest

    steps:
    # Récupérer le dépôt
    - name: Récupérer le code
      uses: actions/checkout@v4

    # Configurer Python
    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    # Installer les dépendances
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Exécuter les tests unitaires
    - name: Exécuter les tests
      run: |
        pytest tests/